name: Bump release version, build-push image and publish SDK

on:
  push:
    branches:
      - release

env:
  NODE_VERSION: 24.x
  PYTHON_VERSION: 3.x
  RELEASE_BRANCH: release

jobs:
  build-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    outputs:
      new_tag: ${{ steps.without_v.outputs.tag }}
      changelog: ${{ steps.tag_version.outputs.changelog }}

    steps:
      - uses: actions/checkout@v7

      ## Commit message examples for Release type (patch|minor|major) can be found:
      ## https://github.com/mathieudutour/github-tag-action
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: ${{ env.RELEASE_BRANCH }}

      - name: Strip 'v' from the tag
        id: without_v
        run: |
          TAG=${{ steps.tag_version.outputs.new_tag }}
          WITHOUT_V=${TAG#v}
          echo "tag=$WITHOUT_V" >> $GITHUB_OUTPUT

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
